[tool.poetry]
name = "dmc-docs"
version = "0.1.0"
description = "Official documentation for Dash Mantine Components library. This documentation is entirely created using components from dash-mantine-components."
authors = ["Snehil Vijay <snehilvj@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
dash = "^2.0.0"
dash-mantine-components = "^0.6.0"
dash-iconify = "^0.1.0"
dash-labs = "^1.0.1"
mistune = "^2.0.2"
pandas = "^1.3.5"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
